import type { Category, Customer, Tool, Rental, ShopSettings } from '../types/database';

export const INITIAL_SETTINGS: ShopSettings = {
  id: 'set-001',
  shop_name: 'Wayanaad Tool Rentals',
  owner_name: 'Moosa Ikka',
  phone: '9847012345',
  address: 'Main Road, Panamaram, Wayanad, Kerala',
  currency: '₹',
  timezone: 'Asia/Kolkata',
  updated_at: new Date().toISOString(),
};

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-drilling', name: 'Drilling & Chipping', description: 'Electric drills, hammer drills, chipping machines', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-cutting', name: 'Cutting & Grinding', description: 'Tile cutters, concrete cutters, angle grinders', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-cleaning', name: 'Washing & Cleaning', description: 'Car washers, high pressure washers, blowers', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-pumps', name: 'Pumps & Motors', description: 'Water pumps, submersible pumps, motor pumps', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-welding', name: 'Welding & Electrical', description: 'Arc welding sets, generators, extension boards', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-construction', name: 'Construction & Lifting', description: 'Mixer machines, vibrators, ladders, jacks, scaffolding', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'Afsal',
    phone: '9847123456',
    address: 'Panamaram, Wayanad',
    notes: 'Regular electrician contractor',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-002',
    name: 'Riyas',
    phone: '9745987654',
    address: 'Kozhikode Town',
    notes: 'House construction client',
    created_at: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-003',
    name: 'Nihad',
    phone: '9633112233',
    address: 'Kunnamangalam',
    notes: 'Plumber',
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust-004',
    name: 'Basheer',
    phone: '9895443322',
    address: 'Kalpetta',
    notes: 'Painter contractor',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_TOOLS: Tool[] = [
  // Drilling
  { id: 'tool-001', name: 'Drilling Machine', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'DR-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-002', name: 'Drilling Machine', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'DR-02', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-003', name: 'Drilling Machine', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'DR-03', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-004', name: 'Drilling Machine', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'DR-04', condition: 'GOOD', status: 'RENTED', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-005', name: 'Hammer Drill', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'HD-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-006', name: 'Chipping Machine', category_id: 'cat-drilling', category_name: 'Drilling & Chipping', tool_code: 'CH-01', condition: 'NEEDS_MAINTENANCE', status: 'MAINTENANCE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // Cutting & Grinding
  { id: 'tool-007', name: 'Cutter', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'CUT-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-008', name: 'Cutter', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'CUT-02', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-009', name: 'Concrete Cutter', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'CC-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-010', name: 'Tile Cutter', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'TC-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-011', name: 'Angle Grinder', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'GR-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-012', name: 'Angle Grinder', category_id: 'cat-cutting', category_name: 'Cutting & Grinding', tool_code: 'GR-02', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // Cleaning
  { id: 'tool-013', name: 'Car Washer', category_id: 'cat-cleaning', category_name: 'Washing & Cleaning', tool_code: 'CW-01', condition: 'GOOD', status: 'RENTED', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-014', name: 'Car Washer', category_id: 'cat-cleaning', category_name: 'Washing & Cleaning', tool_code: 'CW-02', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-015', name: 'Pressure Washer', category_id: 'cat-cleaning', category_name: 'Washing & Cleaning', tool_code: 'CW-03', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-016', name: 'Air Compressor', category_id: 'cat-cleaning', category_name: 'Washing & Cleaning', tool_code: 'CMP-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-017', name: 'Blower', category_id: 'cat-cleaning', category_name: 'Washing & Cleaning', tool_code: 'BL-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

  // Water Pumps & Electrical
  { id: 'tool-018', name: 'Water Pump', category_id: 'cat-pumps', category_name: 'Pumps & Motors', tool_code: 'WP-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-019', name: 'Welding Machine', category_id: 'cat-welding', category_name: 'Welding & Electrical', tool_code: 'WEL-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-020', name: 'Mixer Machine', category_id: 'cat-construction', category_name: 'Construction & Lifting', tool_code: 'MIX-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-021', name: 'Ladder', category_id: 'cat-construction', category_name: 'Construction & Lifting', tool_code: 'LAD-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'tool-022', name: 'Hydraulic Jack', category_id: 'cat-construction', category_name: 'Construction & Lifting', tool_code: 'JK-01', condition: 'GOOD', status: 'AVAILABLE', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

const nowMs = Date.now();
const threeHoursAgo = new Date(nowMs - 3 * 3600 * 1000 + 25 * 60 * 1000).toISOString(); // 03h 25m ago
const yesterdayAgo = new Date(nowMs - 22 * 3600 * 1000).toISOString(); // 22h ago

export const INITIAL_RENTALS: Rental[] = [
  {
    id: 'rent-1001',
    rental_code: 'R-1001',
    customer_id: 'cust-001',
    customer_name: 'Afsal',
    customer_phone: '9847123456',
    customer_address: 'Panamaram, Wayanad',
    tool_id: 'tool-004',
    tool_name: 'Drilling Machine',
    tool_code: 'DR-04',
    category_name: 'Drilling & Chipping',
    started_at: threeHoursAgo,
    expected_return_at: new Date(nowMs + 5 * 3600 * 1000).toISOString(),
    status: 'ACTIVE',
    rental_amount: 0,
    deposit_amount: 0,
    late_fee: 0,
    damage_fee: 0,
    other_fee: 0,
    total_amount: 0,
    created_at: threeHoursAgo,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rent-1002',
    rental_code: 'R-1002',
    customer_id: 'cust-004',
    customer_name: 'Basheer',
    customer_phone: '9895443322',
    customer_address: 'Kalpetta',
    tool_id: 'tool-013',
    tool_name: 'Car Washer',
    tool_code: 'CW-01',
    category_name: 'Washing & Cleaning',
    started_at: yesterdayAgo,
    expected_return_at: new Date(nowMs - 2 * 3600 * 1000).toISOString(), // Overdue by 2 hours
    status: 'ACTIVE',
    rental_amount: 0,
    deposit_amount: 500,
    late_fee: 0,
    damage_fee: 0,
    other_fee: 0,
    total_amount: 0,
    created_at: yesterdayAgo,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rent-1000',
    rental_code: 'R-1000',
    customer_id: 'cust-002',
    customer_name: 'Riyas',
    customer_phone: '9745987654',
    customer_address: 'Kozhikode Town',
    tool_id: 'tool-014',
    tool_name: 'Car Washer',
    tool_code: 'CW-02',
    category_name: 'Washing & Cleaning',
    started_at: new Date(nowMs - 45 * 3600 * 1000).toISOString(),
    returned_at: new Date(nowMs - 27 * 3600 * 1000).toISOString(), // 17h 45m duration
    status: 'RETURNED',
    rental_amount: 700,
    deposit_amount: 0,
    late_fee: 0,
    damage_fee: 0,
    other_fee: 0,
    total_amount: 700,
    return_condition: 'GOOD',
    payment_status: 'PAID',
    payment_method: 'CASH',
    amount_paid: 700,
    created_at: new Date(nowMs - 45 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rent-0999',
    rental_code: 'R-0999',
    customer_id: 'cust-003',
    customer_name: 'Nihad',
    customer_phone: '9633112233',
    customer_address: 'Kunnamangalam',
    tool_id: 'tool-011',
    tool_name: 'Angle Grinder',
    tool_code: 'GR-01',
    category_name: 'Cutting & Grinding',
    started_at: new Date(nowMs - 72 * 3600 * 1000).toISOString(),
    returned_at: new Date(nowMs - 48 * 3600 * 1000).toISOString(),
    status: 'RETURNED',
    rental_amount: 300,
    deposit_amount: 0,
    late_fee: 0,
    damage_fee: 0,
    other_fee: 0,
    total_amount: 300,
    return_condition: 'GOOD',
    payment_status: 'PAID',
    payment_method: 'UPI',
    amount_paid: 300,
    created_at: new Date(nowMs - 72 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
